services:
  web:
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
    container_name: url_shortener_api_web
    ports:
      - '8080:8080'
    volumes:
      - .:/app
      - /app/vendor
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:latest
    container_name: url_shortener_api_db
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD']
      timeout: 20s
      retries: 10

networks:
  default:
    driver: bridge
